version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: poker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poker
      MYSQL_USER: poker
      MYSQL_PASSWORD: poker123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: poker-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/poker?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: poker
      SPRING_DATASOURCE_PASSWORD: poker123
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data: 